### ISSUE TITLE
aurorae theme: huge borders with font scaling

### ISSUE THREAD

**Issue by scarwire** [EliverLara/Sweet#34] opened 2019-04-25 13:16 UTC
First of all, thanks for this beautiful theme!

There's a problem with the aurorae window decorations which I've seen on several [other themes](https://github.com/andreyorst/Breezemite/issues/8): if you increase the font dpi setting in KDE to more than 96, the window borders get really, really big. This happens on a lot of themes, but not all, so I don't know if it's a bug in a lot of themes or a bug in Plasma. 

To reproduce: open kde system settings -> fonts -> force fonts dpi: 120 -> ok. Log out and back in. Open any window and you'll see the problem.

**Comment by EliverLara** [comment] 2019-04-25 21:27
Hi, thanks for reporting!, I've reproduced the issue and the border looks really big, so as a temporary solution I have adjusted the values ​​in the rc file, if you want you can download it [here](https://gist.github.com/EliverLara/55ad80c2a685cced9f63123f3b82d86b) while I find an official solution.

**Comment by ChordMankey** [comment] 2019-05-16 05:31
Hi, I just tried applying the fix that you provided by copying the file from your fix into ~/.local/share/aurorae/themes/Sweet-Dark

And although it fixed the window being larger than the title-bar issue, another peculiar issue appeared that I'll [describe with an image](https://imgur.com/a/qr4Eb6U)

Just to clarify, I'm using the collection of the themes you've created for KDE, just felt the need to clarify because this repo seems to contain (also) the GTK theme.

Thanks for the help!

**Comment by thewhiteh4t** [comment] 2019-05-17 13:45
i am also having this same issue, and only my konsole and panel are translucent / blurred not settings app or dolphin
![Screenshot_20190517_191302](https://user-images.githubusercontent.com/36354846/57932214-0a255a80-78d8-11e9-81a8-7fe8319cd01a.png)

**Comment by thewhiteh4t** [comment] 2019-05-17 13:56
Forcing font dpi to 96 fixes this issue

**Comment by EliverLara** [comment] 2019-05-18 18:28
Hi @ChordMankey  and @thewhiteh4t thanks for reporting!, @thewhiteh4t Did you try to use the solution I proposed before changing font dpi? about  dolhin blur, thats achieve by the [kvantum](https://www.pling.com/p/1294013/) theme.

**Comment by thewhiteh4t** [comment] 2019-05-18 22:16
@EliverLara no actually when i switched to kde, initially all the fonts were very small by default at size 10 so i increased them to 14, then i read about dpi and forced it to 96 which made fonts very big so i reduced font size back to 10 and kept dpi at 96 and your theme works, so i did not try your solution.

okay i will try kvantum theme.

**Comment by zevulos** [comment] 2019-05-23 21:49
Im also getting this problem, i have edited the RC file to fix this but the text at the top of windows is black. I have tried chaning Textcolor to 255,255,255,255 for white but it didnt work. Can you help ?

**Comment by EliverLara** [comment] 2019-08-18 20:28
That should be fixed now!

**Comment by CiriousJoker** [comment] 2019-11-03 15:16
What did you do to fix this issue? The issue seems to be present in a lot of themes, perhaps this fix can easily be ported to other themes.

**Comment by CiriousJoker** [comment] 2019-11-03 15:17
What did you do to fix this issue? The issue seems to be present in a lot of themes, perhaps this fix can easily be ported to other themes.

@EliverLara

**Closed** 2020-07-13 17:00 UTC
Labels: DE: KDE

**Comment by dreamcat4** [comment] 2022-05-22 15:41
> Asking again since this is still an issue with many themes.

Am using Otto theme here (but only for window decorations). So this is assuming the theme name 'Otto' is set in 'Appearance' --> 'Window' Decorations'. And that `Window Border Size` is set to `No borders`

And the borders are very thick still.

This is what I had to do:

```sh
# replace 'Otto' below with YOUR_THEME_NAME
cd ~/.local/share/aurorae/themes/Otto
cp Ottorc Ottorc.bak
```

And there is a config file there called `Ottorc`

Find and change the following lines:

```sh
# this one is entirely optional
Shadow=true --> change to false

# these are the critical options, all of the 'Padding...' ones
PaddingTop=35 --> change to 32
PaddingBottom=90 --> change to 74
PaddingRight=76 --> change to 66
PaddingLeft=76 --> change to 66
```

Now go back to the KDE System Settings app. And under 'Appearance' --> 'Window Decorations', you need to switch to a different theme (any other one). And hit 'Apply'. Then go back to your preferred chosen theme (in my example here it's 'Otto'). So you re-select it and then hit 'Apply' button a 2nd time. And it should re-load the theme. And be re-reading the `Ottorc` config file.

...really have no idea why this works, but it worked for me today. And it was after reading somebody mention the work 'padding'

If you want to play with this options, you will find that drastically changing the padding will show it's a kind of extra shadow border being drawn underneat (behind) the actual core window decorations. To just give some illusion of a drop shadow styling or whatever. Like a background that moves along with the window.

So clearly this bug in plasma 'wherever' now occurs if you see this where this behind box is now being indexed from. It is significantly smaller (shrunk) in dimensions than the actual window itself which it is supposed to be tracking and following. By some large number of pixels (like 30 or 50 pixels).

... i have no idea why this is, or where the bug is occuring in plasma. Please don't shoot the messenger. But there should be a proper bug filed against it to whichever responsibles within kde / plasma people (i believe so?). Or otherwise it's a QT bug and then in the QT libs underneath.

OK please post elsewhere this solution. Like on stack since its not purely specific only to this 1 theme. Many thanks.
