### ISSUE TITLE
Dark background and dark text in GnuCash with Sweet Dark

### ISSUE THREAD

**Issue by chipotledonut** [EliverLara/Sweet#119] opened 2020-10-31 19:41 UTC
Using ther last update there's this bug again

[Solved bug](https://github.com/EliverLara/Sweet/issues/94)

**Comment by EliverLara** [comment] 2020-10-31 20:21
Hi, it supossed to be fixed with [this commit](https://github.com/EliverLara/Sweet/commit/ef205d53e6e8409631a8c3c6604313bc642b41f6), I'm using the last version  of `sweet` and `gnucash`(v4.2) and the issue is not present:

![Screenshot_20201031_141555](https://user-images.githubusercontent.com/9838260/97789218-41e39900-1b84-11eb-9cc8-794b4877e48a.png)

**Comment by chipotledonut** [comment] 2020-11-26 15:29
Hi there, I'm using last version of `sweet` and `gnucash` (v3.8 the one in official Ubuntu packages) and the issue is present.

**Comment by chipotledonut** [comment] 2020-12-02 17:04
If I reverted to version 2020-07-13 of Sweet Dark the field entry is fixed. It's the one you released with the fix. Somewhere in the new updates it was broken again, @EliverLara.

I'm on Ubuntu Budgie 20.04, Gnucash 3.8 from Ubuntu repo.

**Comment by chipotledonut** [comment] 2021-01-01 17:08
Just to let you know,

Replacing

`#gnc-id-main-window entry.gnc-class-register-foreground {
  background: transparent;
  border: none;
  box-shadow: none; }`

in gtk-dark.css and gtk.css with

`.GncMainWindow entry.register-foreground {
  background: transparent;
  border: none; }`

Solved the issue. It might be beacuse my old GnuCash version.

Thanks for this awesome theme.

**Closed** 2021-01-22 19:52 UTC
